package com.musicweb.test;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Playlists generated by hbm2java
 */
@Entity
@Table(name = "playlists", catalog = "heroku_6206d67ecbf53a3")
public class Playlists implements java.io.Serializable {

	private Integer playlistId;
	private Users users;
	private String name;
	private String decription;
	private Set<Songs> songses = new HashSet<Songs>(0);

	public Playlists() {
	}

	public Playlists(Users users, String name) {
		this.users = users;
		this.name = name;
	}

	public Playlists(Users users, String name, String decription, Set<Songs> songses) {
		this.users = users;
		this.name = name;
		this.decription = decription;
		this.songses = songses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "playlist_id", unique = true, nullable = false)
	public Integer getPlaylistId() {
		return this.playlistId;
	}

	public void setPlaylistId(Integer playlistId) {
		this.playlistId = playlistId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "decription", length = 100)
	public String getDecription() {
		return this.decription;
	}

	public void setDecription(String decription) {
		this.decription = decription;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "playlistses")
	public Set<Songs> getSongses() {
		return this.songses;
	}

	public void setSongses(Set<Songs> songses) {
		this.songses = songses;
	}

}
