package com.musicweb.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "musicwebdb", uniqueConstraints = @UniqueConstraint(columnNames = "account"))
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer userId;
	private String account;
	private String password;
	private String name;
	private int type;
	private Set<Playlists> playlistses = new HashSet<Playlists>(0);

	public Users() {
	}

	public Users(String account, String password, String name, int type) {
		this.account = account;
		this.password = password;
		this.name = name;
		this.type = type;
	}

	public Users(String account, String password, String name, int type, Set<Playlists> playlistses) {
		this.account = account;
		this.password = password;
		this.name = name;
		this.type = type;
		this.playlistses = playlistses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "account", unique = true, nullable = false, length = 15)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "password", nullable = false, length = 15)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Playlists> getPlaylistses() {
		return this.playlistses;
	}

	public void setPlaylistses(Set<Playlists> playlistses) {
		this.playlistses = playlistses;
	}

}
